In [1]:
import duckdb
import pandas as pd

con = duckdb.connect("data/home_credit.db")

In [2]:
tables = con.sql("SHOW TABLES").df()

tables

                    name
0       POS_CASH_balance
1       application_test
2      application_train
3                 bureau
4         bureau_balance
5    credit_card_balance
6  installments_payments
7   previous_application

In [3]:
n_applications_train = con.sql("SELECT COUNT(*) FROM application_train").fetchone()[0]
n_applications_test = con.sql("SELECT COUNT(*) FROM application_test").fetchone()[0]

print(f"Number of applications: {n_applications_train} (train) {n_applications_test} (test)")

Number of applications: 307511 (train) 48744 (test)

In [4]:
example_application = con.sql("SELECT * FROM application_train LIMIT 5").df()

example_application

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0